#!/usr/bin/python3

import sys
import dbus


if (len(sys.argv) != 2):
    print("Usage: %s <network>" % (sys.argv[0]))
    sys.exit(1)

bus = dbus.SystemBus()
network = dbus.Interface(bus.get_object("net.connman.iwd", sys.argv[1]),
                                    "net.connman.iwd.Network")
network.Connect()
