#!/usr/bin/python3

import dbus
import sys

if len(sys.argv) != 2:
        print("Usage: %s <device>" % (sys.argv[0]))
        sys.exit(1)

bus = dbus.SystemBus()
device = dbus.Interface(bus.get_object("net.connman.iwd", sys.argv[1]),
                        "org.freedesktop.DBus.Properties")

print("WDS: %d" % device.Get("net.connman.iwd.Device", "WDS"));
