#!/usr/bin/python3

import sys
import dbus

if (len(sys.argv) != 2 and len(sys.argv) != 3):
    print("Usage: %s <device> [pin]" % (sys.argv[0]))
    sys.exit(1)

bus = dbus.SystemBus()
wsc = dbus.Interface(bus.get_object("net.connman.iwd", sys.argv[1]),
                                    "net.connman.iwd.WiFiSimpleConfiguration")

if (len(sys.argv) == 3):
    pin = sys.argv[2]
else:
    pin = wsc.GeneratePin()
    print("Please use '%s' as the PIN" % (pin))

wsc.StartPin(pin, timeout=125)
