#!/bin/sh

if [ -f config.status ]; then
	make maintainer-clean
fi

./bootstrap && \
    ./configure --enable-maintainer-mode \
		--enable-debug \
		--localstatedir=/var \
		--prefix=/usr $* \
		--sysconfdir=/etc/iwd \
		--with-dbusconfdir=/etc
