#!/bin/sh

if [ -f config.status ]; then
	make maintainer-clean
fi

./bootstrap && \
    ./configure --enable-maintainer-mode \
		--enable-debug \
		--prefix=/usr \
		--localstatedir=/var \
		--enable-ofono \
		--enable-sim-hardcoded \
		--disable-dbus-policy \
		--disable-systemd-service $*
