#! /bin/sh

scripts/config --enable CONFIG_MAC80211_HWSIM
scripts/config --enable CONFIG_DRIVER_NL80211
scripts/config --enable CONFIG_VLAN_8021Q

scripts/config --enable CONFIG_CRYPTO_USER_API_AKCIPHER
scripts/config --enable CONFIG_CRYPTO_USER_API_SKCIPHER
scripts/config --enable CONFIG_CRYPTO_USER_API_HASH
scripts/config --enable CONFIG_KEY_DH_OPERATIONS
scripts/config --enable CONFIG_ASYMMETRIC_KEY_TYPE
scripts/config --enable CONFIG_PKCS8_PRIVATE_KEY_PARSER

scripts/config --enable CONFIG_HW_RANDOM_VIRTIO
scripts/config --enable CONFIG_HW_RANDOM_INTEL
#scripts/config --enable CONFIG_HW_RANDOM_AMD
