#! /bin/sh

scripts/config --enable CONFIG_MAC80211_HWSIM
scripts/config --enable CONFIG_NLMON
scripts/config --enable CONFIG_VLAN_8021Q

scripts/config --enable CONFIG_CRYPTO_USER_API_SKCIPHER
scripts/config --enable CONFIG_CRYPTO_USER_API_HASH
scripts/config --enable CONFIG_CRYPTO_RSA
scripts/config --enable CONFIG_CRYPTO_AES_X86_64
scripts/config --enable CONFIG_CRYPTO_AES_NI_INTEL
scripts/config --enable CONFIG_CRYPTO_MD4
scripts/config --enable CONFIG_CRYPTO_SHA1_SSSE3
scripts/config --enable CONFIG_CRYPTO_SHA256_SSSE3
scripts/config --enable CONFIG_CRYPTO_SHA512_SSSE3
scripts/config --enable CONFIG_CRYPTO_ECB
scripts/config --enable CONFIG_CRYPTO_CMAC
scripts/config --enable CONFIG_CRYPTO_DES
scripts/config --enable CONFIG_CRYPTO_DES3_EDE_X86_64
scripts/config --enable CONFIG_KEY_DH_OPERATIONS
scripts/config --enable CONFIG_ASYMMETRIC_KEY_TYPE
scripts/config --enable CONFIG_ASYMMETRIC_PUBLIC_KEY_SUBTYPE
scripts/config --enable CONFIG_X509_CERTIFICATE_PARSER
scripts/config --enable CONFIG_PKCS7_MESSAGE_PARSER
scripts/config --enable CONFIG_PKCS8_PRIVATE_KEY_PARSER

scripts/config --enable CONFIG_HW_RANDOM_VIRTIO
scripts/config --enable CONFIG_HW_RANDOM_INTEL
#scripts/config --enable CONFIG_HW_RANDOM_AMD
scripts/config --enable CONFIG_SECURITYFS
